### ISSUE TITLE
[Bug] Text prompts cannot be confirmed with Enter key

### ISSUE THREAD

**Issue by sdasda7777** [OpenPonk/openponk#76]
After pressing Enter, the cursor gets moved to the beginning of the line, but the prompt is not confirmed.

![image](https://user-images.githubusercontent.com/17746796/194655702-ea85e44d-24fd-4a53-8b12-6ff619e62b5f.png)

**Comment by sdasda7777** [comment]
Tracked it down to Spec, created an [issue](https://github.com/pharo-spec/Spec/issues/1348).

**Comment by sdasda7777** [comment]
@JanBliznicenko Hey, I noticed that the `MorphicUIManager`'s `request:` (which is used when creating Note elements) can be confirmed with the press of enter key. Is there a reason why it's not used more?

```smalltalk
MorphicUIManager new request: 'Provide your name, please'
```
It can also do initial value:

```smalltalk
MorphicUIManager new request: 'Provide new element name, please' initialAnswer: 'old element name'
```

**Comment by JanBliznicenko** [comment]
Generally I try to use Spec (that internally may use Morphic or other backend) instead of Morphic directly as it is usually easier and same across all aspects of the UI. Yet in this case, the dialog might be easily replaced with its Morphic counterpart directly, true. Well, we also have a closed-source extension of OP that extends this dialog for some purposes that might require more changes to do that on Morphic level, but might be doable. I will try to take a look into it.
