### ISSUE TITLE
[Bug] Mode generalization not accepted by model verificator

### ISSUE THREAD

**Issue by sdasda7777** [OpenPonk/openponk#77]
According to the verificator, a Mode cannot be subtype of another Mode. However according to the written constraints and the examples from the [OntoUML documentation](https://ontouml.readthedocs.io/en/latest/classes/aspects/mode/index.html), this should most likely be allowed.

![image](https://user-images.githubusercontent.com/17746796/194660021-d9db9ae9-6cfd-496d-a34c-846cd412d3d9.png)

**Comment by JanBliznicenko** [comment]
Yes, there seems to be inconsistency even in the documentation (from which OP verifications are built), thank you. Passing the problem to colleagues responsible for documentation and verifications.

**Comment by JanBliznicenko** [comment]
According to my colleagues, it seems this behavior is correct and there is an error in the documentation which they will fix. Mode has its identity and cannot therefore be subtyped by another mode with its own identity - only by subkind, phase and role. Since I am personally not that knowledgable about OntoUML, ask @roper79 or your tutorials teacher if you are interested in more info :)
