### ISSUE TITLE
[Bug] Immovable line angles

### ISSUE THREAD

**Issue by sdasda7777** [OpenPonk/openponk#79]
When executing a sequence of line midpoint drags and line angle collapses, result can be an angle (circled red) that is completely immovable. This immovable angle is persistent after saving the project, and only solution known to me is the deletion of the whole association.

![image](https://user-images.githubusercontent.com/17746796/199336556-2150bce1-c8c9-4243-943e-4572c5b8ae09.png)

![image](https://user-images.githubusercontent.com/17746796/199336690-8acdf059-c652-4e55-add2-f993712bb281.png)

![image](https://user-images.githubusercontent.com/17746796/199336772-102873b9-fbe6-4d65-8507-2b91a550a470.png)

![image](https://user-images.githubusercontent.com/17746796/199337168-78e57ea3-acc5-4e51-8f71-6b12fe2dbfd9.png)

**Comment by JanBliznicenko** [comment]
Thank you. Fix is available in today's nightly build. The fix should work for both new and already saved instances of such immovable points.

**Comment by sdasda7777** [comment]
I'm not sure why, but there don't seem to be any nightly builds available for download on this repo, and the newest nightly build reachable from [the download site](https://openponk.org/#download) seems to be 9 days old.

**Comment by JanBliznicenko** [comment]
> I'm not sure why, but there don't seem to be any nightly builds available for download on this repo, and the newest nightly build reachable from [the download site](https://openponk.org/#download) seems to be 9 days old.

This repository is core of the openponk without any kinds of diagrams/notations, so there is not much to download for this repo (except for development of new kind of diagram).
That's why the download section of openponk.org only links to other repos with builds with specific types of models, like class-editor for UML class diagrams and OntoUML.

All the repositories pointed by openponk.org have this one (OpenPonk/openponk) as a dependency.
There are usually two kinds of files in these build pages (like https://github.com/OpenPonk/class-editor/releases/tag/nightly ). 3 are the actual executable builds for each platform (win, linux, mac) and then 2 are archives with source codes. Since only the core of openponk (the dependency) has changed, the source code of the class-editor repository/plugin itself did not change so that's why the source code archive is old (it was last changed 9 days ago), yet those executables are more recent

**Comment by sdasda7777** [comment]
Ah, I see, thank you.
