### ISSUE TITLE
[Bug] Error when listing elements by type when Note is present

### ISSUE THREAD

**Issue by sdasda7777** [OpenPonk/openponk#82]
![image](https://user-images.githubusercontent.com/17746796/200069483-8046bf5d-3688-4b40-adab-e79ba491d25d.png)

![image](https://user-images.githubusercontent.com/17746796/200069582-a277e811-f01f-4c1d-a9e5-9aca0e156857.png)

![image](https://user-images.githubusercontent.com/17746796/200069706-18dea553-0ada-43b1-b466-83db8738036a.png)

**Comment by sdasda7777** [comment]
@JanBliznicenko I tried looking into this as well, but I'm not completely sure how to approach it. It would definitely be possible to just add these methods to Note, but I don't think that's exactly a good idea from object design perspective. Another solution might be to not show Notes on there at all, but someone might want to be able to hide them, so it's also probably not the best. Last option I can think of would be to add all elements something like a "displayName" method, and return umlClassName in UML elements and "Note" for Notes.

**Comment by sdasda7777** [comment]
Two more things:

I noticed that OPNote and OPUMLElement actually don't share any class in the hierarchy besides Object - that means that for the third approach the hierarchy would probably also have to be reworked (having two completely unrelated classes have methods sharing name and calling the two unrelated methods based on the object at hand just screams bad OOP, imo).

I also noticed that OPNote doesn't have option to hide it, unlike most of the objects. That means the second approach might actually be the correct one?

**Comment by JanBliznicenko** [comment]
Yes, the Note (and Boundary) are a little special. While all the other elements are parts of the model (root UML package in this case), Note and Boundary are completely outside of the model (even though they have model classes OPNote and OPBoundary).
And as you correctly say, they should not even support the hiding and showing, because "show" basically means "create diagram representation of the model element" and "hide" means "remove diagram representation of the model element, but keep the model element itself". Since note and boundary are not model elements, hide = remove and show makes no sense.
